### ISSUE TITLE
[建议]增加转换后删除源文件功能、自启动功能。

### ISSUE THREAD

**Issue by smdx** [hrpzcf/ImageCvt#1]
作者大佬你好，这软件太实用了感谢分享。希望可以增加转换后自动删除源文件选项，开机自启动最小化到托盘功能。谢谢

**Comment by hrpzcf** [comment]
1. 已经添加了转换成功后自动删除原文件选项和启动后不显示主窗口选项；
2. 现在软件可能因为使用了监控文件变动 API 和内嵌了 libpng/libjpeg-turbo/libwebp 等第三方库的原因很容易被杀毒软件误报，开机自启动功能不打算添加了，以免雪上加霜。软件的自动启动可以自行手动实现。

**Comment by smdx** [comment]
好的非常感谢，马上下载使用。
