### ISSUE TITLE
开机启动提示设置加载失败

### ISSUE THREAD

**Issue by smdx** [hrpzcf/ImageCvt#2]
作者好，今天开机时遇到个错误提示：设置加载失败：XML文档（OO）中有错误
程序放置目录：D:\Soft\WebpCvt、快捷方式到Windows\Start Menu\Programs\Startup开机启动。
![2024-03-08_092621](https://github.com/hrpzcf/ImageCvt/assets/9279217/3624f108-e883-42bb-b8a0-f4fc767cddc8)

**Comment by hrpzcf** [comment]
可能是因为没退出软件直接关机导致更改过的设置没有保存下来或者设置文件损坏导致的，我修复一下试试
